// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PinkPoint.DataAccess.Helpers;

#nullable disable

namespace PinkPoint.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221112100319_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PinkPoint.Data.Domain.User", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("birth_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("creation_tsz")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("delete_tsz")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("gender")
                        .HasColumnType("int");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("last_updated_tsz")
                        .HasColumnType("datetime2");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("status_active")
                        .HasColumnType("bit");

                    b.Property<bool?>("status_visibility")
                        .HasColumnType("bit");

                    b.HasKey("user_id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userid = new Guid("c94b6b4b-b72a-4ad9-8ee1-357128f3bd95"),
                            bio = "test aşamsında kullanıcı biyografisi",
                            birthdate = new DateTime(1993, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            creationtsz = new DateTime(2022, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "hayrettin.gov@gmail.com",
                            firstname = "Hayrettin",
                            gender = 1,
                            lastname = "Göv",
                            lastupdatedtsz = new DateTime(2022, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            phone = "05070053711",
                            statusactive = true,
                            statusvisibility = true
                        },
                        new
                        {
                            userid = new Guid("a94b6b4b-b72a-4ad9-8ee1-357128f3bd95"),
                            bio = "test aşamsında kullanıcı biyografisi",
                            birthdate = new DateTime(1990, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            creationtsz = new DateTime(2022, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "victoria@gmail.com",
                            firstname = "Victoria",
                            gender = 2,
                            lastname = "Mercedes",
                            lastupdatedtsz = new DateTime(2022, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            phone = "05070053723",
                            statusactive = true,
                            statusvisibility = true
                        },
                        new
                        {
                            userid = new Guid("b94b6b4b-b72a-4ad9-8ee1-357128f3bd95"),
                            bio = "test aşamsında kullanıcı biyografisi",
                            birthdate = new DateTime(1992, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            creationtsz = new DateTime(2022, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "angela@gmail.com",
                            firstname = "Angela",
                            gender = 2,
                            lastname = "Bear",
                            lastupdatedtsz = new DateTime(2022, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            phone = "05070053755",
                            statusactive = true,
                            statusvisibility = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
